config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :tutors do
    get :resume, on: :member
  end
  resources :admins
  resources :departments
  resources :subjects

  resources :topics
  resources :sessions
  resources :hirings, only: [:create, :destroy]

  resources :videos, only: :show
  resources :worksheets, only: :show
  resources :quizzes, only: [:show, :edit, :update] do
    post :grade, on: :member
  end
  resources :certifications, only: :certify do
    get :certify, on: :member
  end

  root 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/links', to: 'static_pages#links', via: 'get'
  match '/signup', to: 'static_pages#signup', via: 'get'
  match '/signin', to: 'students#signin', via: 'post'
  match '/signout', to: 'students#signout',  via: 'post'

end

app/views/admins/edit.html.erb
<% provide(:title, "Edit Admin") %>
<% content_for :pageBar do %>
	<%= link_to "Admins", admins_path %> > <%= link_to @admin.displayName, admin_path(@admin) %> > <%= link_to "Edit", edit_admin_path(@admin) %>
<% end %>

<h1>Edit <%= @admin.displayName %>'s Profile</h1>
<%= form_for(@admin) do |f| %>

	<%= render 'shared/editForm', f: f %>

	<p><%= f.submit "Update Account" %></p>

<% end %>

app/views/admins/index.html.erb
<% provide(:title, "All Admins") %>
<% content_for :pageBar do %>
	<%= link_to "Admins", admins_path %>
<% end %>

<% @admins.each do |admin| %>
	<p><%= link_to admin.displayName, admin %></p>
<% end %>

app/views/admins/new.html.erb
<% provide(:title, 'Sign Up Admin')%>
<% content_for :pageBar do %>
	<%= link_to "Admins", admins_path %> > <%= link_to "Create Admin", new_admin_path %>
<% end %>
<h1>Sign Up Admin</h1>
<%= form_for(@admin) do |f| %>
	
	<%= render 'shared/newForm', f: f %>

	<p><%= f.submit "Create Admin" %></p>

<% end %>

app/views/admins/show.html.erb
<% provide(:title, 'Admin Page') %>
<% content_for :pageBar do %>
	<%= link_to "Admins", admins_path %> > <%= link_to @admin.displayName, admin_path(@admin) %>
<% end %>

<div class="columns large-2 bio">
	<p class="name"><%= @admin.displayName %></p>
	<p><%= @admin.realName unless @admin.realName.blank?%></p>
	<br/>
	<p class="privilege"><%= @admin.privilege == "0" ? "Full Admin" : "Content Admin" %></p>
	<p><%= @admin.email %></p>
	<p><%= @admin.dob unless @admin.dob.blank?%></p>
	<p><%= @admin.gender == "0" ? "Male" : "Female" %></p>
	<p><%= @admin.biography unless @admin.biography.blank?%></p>
	<% if currentAdmin == @admin %>
		<p><%= link_to "Delete Account", @admin, method: :delete,
					data: {confirm: "Are you sure?"} %></p>
	<% end %>
</div>

<div class="columns large-10 main">
	<% if currentAdmin == @admin %>
		<h4>Pending Certifications </h4>
		<% @certifications.each do |cert| %>
			<% if cert.tutor.fileName.present? %>
				<p><%= cert.tutor.displayName %>(<%= cert.tutor.realName %>)
					<%= cert.subject.name %>
					<%= link_to "Resume", resume_tutor_path(cert.tutor), target: "_blank" %>
					<%= link_to "Certify?", certify_certification_path(cert), data: {confirm: "Are you sure?"} %>
				</p>
			<% end %>
		<% end %>
	<% end %>
</div>