config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :tutors do
    get :resume, on: :member
  end
  resources :admins
  resources :departments
  resources :subjects

  resources :topics
  resources :sessions
  resources :hirings, only: [:create, :destroy]

  resources :videos, only: :show
  resources :worksheets, only: :show
  resources :quizzes, only: [:show, :edit, :update] do
    post :grade, on: :member
  end
  resources :certifications, only: :certify do
    get :certify, on: :member
  end

  root 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/links', to: 'static_pages#links', via: 'get'
  match '/signup', to: 'static_pages#signup', via: 'get'
  match '/signin', to: 'students#signin', via: 'post'
  match '/signout', to: 'students#signout',  via: 'post'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :subject
	has_many :videos, dependent: :destroy
	has_many :worksheets, dependent: :destroy
	has_many :quizzes, as: :quizParent, dependent: :destroy

	validates :name, presence: true, length: {maximum: 40}
	validates :description, presence: true, length: {maximum: 4000}
	validates_associated :videos, presence: true
	validates_associated :worksheets, presence: true
	validates_associated :quizzes, presence: true

	accepts_nested_attributes_for :videos, allow_destroy: true
	accepts_nested_attributes_for :worksheets, allow_destroy: true
	accepts_nested_attributes_for :quizzes, allow_destroy: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	include AdminsHelper
	before_action :adminSignedIn, except: [:index, :show]

	def index
		@topics = Topic.all
	end

	def show
		@topic = Topic.find(params[:id])
		@videos = @topic.videos
		@video = @videos.first
		@worksheets = @topic.worksheets
		@quizzes = @topic.quizzes
	end

	def new
		@topic = Topic.new
		@videos = @topic.videos
		@worksheets = @topic.worksheets
		@quizzes = @topic.quizzes
	end

	def create
		@topic = Topic.new(topicParams)
		if @topic.save
			flash[:success] = "Topic Created"
			redirect_to @topic
		else
			render 'new'
		end
	end

	def edit
		@topic = Topic.find(params[:id])
		@videos = @topic.videos
		@worksheets = @topic.worksheets
		@quizzes = @topic.quizzes
	end

	def update
		@topic = Topic.find(params[:id])
		if @topic.update_attributes(topicParams)
			flash[:success] = "Topic Updated"
			redirect_to @topic
		else
			flash[:failure] = "Topic not updated"
			render 'edit'
		end
	end

	def destroy
		@topic = Topic.find(params[:id]).destroy
		flash[:success] = "Topic Deleted"
		redirect_to root_path
	end

	private

		def topicParams
			params.require(:topic).permit(:name, :description, 
				videos_attributes: [:id, :name, :topic_id, :imageFile, :_destroy],
				worksheets_attributes: [:id, :name, :pdfFile, :topic_id, :_destroy],
				quizzes_attributes: [:id, :name, :topic_id, :_destroy])
		end
end

app/views/topics/_editTopic.html.erb
<p><%= f.label :name%>
<%= f.text_field :name%></p>

<p><%= f.label :description%>
<%= f.text_area :description%></p>



<h4>Videos</h4>
<p>Video formats currently supported: ogg, webm</p>
<%= f.fields_for :videos, html:{multipart: true} do |builder| %>
	<p><div class="vid"><%=  builder.text_field :name %></div><br/>
	<%= builder.file_field :imageFile %>
	<%= builder.link_to_remove "Remove Video", data: {confirm: "Are you sure?"} %></p>
<% end %>
<p><%= f.link_to_add "Add Video", :videos %></p>
<br/>


<h4>Worksheets</h4>
<%= f.fields_for :worksheets, html:{multipart: true} do |builder| %>
	<p><div class="pdf"><%=  builder.text_field :name %></div><br/>
	<%= builder.file_field :pdfFile %>
	<%= builder.link_to_remove "Remove Worksheet", data: {confirm: "Are you sure?"} %></p>
<% end %>
<p><%= f.link_to_add "Add Worksheet", :worksheets %></p>
<br/>

<h4>Quizzes</h4>
<%= f.fields_for :quizzes, html:{multipart: true} do |builder| %>
	<p><div class="quiz"><%=  builder.text_field :name %>
	<%= builder.link_to_remove "Remove Quiz", data: {confirm: "Are you sure?"} %></div></p>
<% end %>
<p><%= f.link_to_add "Add Quiz", :quizzes %></p>

app/views/topics/_showGrades.html.erb
<%= link_to "#{text}", quiz_path(difficulty: "#{diff}") %>
<% if studentSignedIn? %>
	<% studentGrades = quiz.grades.where(student_id: currentStudent.id, difficulty: "#{diff}")%>
	<% if !studentGrades.first.nil?%>
		<ul>
			<li>Best score: <%= studentGrades.order(average: :desc).first.average %>%</li>
			<li>Last score: <%= studentGrades.order(created_at: :desc).first.average %>%</li>
			<li>Average score: <%= studentGrades.all.average(:average).round(2) %>%</li>
		</ul>
	<% end %>
<% end %>

app/views/topics/_showQuizzes.html.erb
<% if !@quizzes.empty? %>
	<h5><%= "Quiz".pluralize(@quizzes.count) %></h5>
<% end %>

<% @quizzes.each do |quiz| %>
	<% if adminSignedIn? %>
		<p><%= link_to quiz.name, quiz %></p>
	<% else %>
		<ul><%= quiz.name %>
			<li><%= render 'showGrades', diff: "easy", quiz: quiz, text: "Easy"%></li>
			<li><%= render 'showGrades', diff: "med", quiz: quiz, text: "Medium"%></li>
			<li><%= render 'showGrades', diff: "hard", quiz: quiz, text: "Hard"%></li>
		</ul>
	<% end %>
<% end %>

app/views/topics/_showVideos.html.erb
<% if !@videos.empty? %>
	<h5><%= "Video".pluralize(@videos.count) %></h5>
<% end %>

<% if @videos.count > 1 || @videos.count == 0 %>
	<% @videos.each do |video| %>
		<p><%= link_to video.name, video%>
			<% if studentSignedIn? && currentStudent.viewed?(video)%>
				Viewed
			<% end %> 
		</p>
	<% end %>
<% else %>
	<%= video_tag "/topics/#{@video.topic.id}/videos/" + @video.filename, :controls => true %>
<% end %>

app/views/topics/edit.html.erb
<% provide(:title, "Edit Topic") %>
<% content_for :pageBar do %>
	<%= link_to "Topics", topics_path %> > <%= link_to @topic.name, topic_path(@topic) %> > <%= link_to "Edit", edit_topic_path(@topic) %>
<% end %>

<%= nested_form_for @topic, html:{multipart: true} do |f| %>
	<%= render 'shared/errors', object: f.object%>
	
	<%= render 'editTopic', f: f %>

	<%= f.submit "Edit Topic"%>
<% end %>

<p><%= link_to "Delete Topic", @topic, method: :delete, 
				data: {confirm: "Are you sure?"} %></p>

app/views/topics/index.html.erb
<% provide(:title, "Topics") %>
<% content_for :pageBar do %>
	<%= link_to "Topics", topics_path %>
<% end %>

<h2>All Topics</h2>

<% if adminSignedIn? %>
	<p><%= link_to "Create New Topic", new_topic_path %></p>
<% end %>

<% @topics.each do |topic| %>
	<p><%= link_to topic.name, topic%></p>
<% end %>

app/views/topics/new.html.erb
<% provide(:title, "Create Topic") %>
<% content_for :pageBar do %>
	<%= link_to "Topics", topics_path %> > <%= link_to "Create Topic", new_topic_path %>
<% end %>

<%= nested_form_for @topic, html:{multipart: true} do |f| %>
	<%= render 'shared/errors', object: f.object%>
	
	<%= render 'editTopic', f: f %>

	<%= f.submit "Create Topic"%>
<% end %>

app/views/topics/show.html.erb
<% provide(:title, @topic.name) %>
<% content_for :pageBar do %>
	<%= link_to "Topics", topics_path %> > <%= link_to @topic.name, topic_path(@topic) %>
<% end %>
<p><%= @topic.name %></p>
<p><%= @topic.description %></p>

<%= render 'showVideos' %>



<% if !@worksheets.empty? %>
	<h5><%= "Worksheet".pluralize(@worksheets.count) %></h5>
<% end %>

<% @worksheets.each do |worksheet| %>
	<p><%= link_to worksheet.name, worksheet, target: "_blank" %></p>
<% end %>

<%= render 'showQuizzes' %>

<% if adminSignedIn?%>
	<br/><p><%= link_to "Edit Topic", edit_topic_path %></p>
<% end %>