config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :tutors do
    get :resume, on: :member
  end
  resources :admins
  resources :departments
  resources :subjects

  resources :topics
  resources :sessions
  resources :hirings, only: [:create, :destroy]

  resources :videos, only: :show
  resources :worksheets, only: :show
  resources :quizzes, only: [:show, :edit, :update] do
    post :grade, on: :member
  end
  resources :certifications, only: :certify do
    get :certify, on: :member
  end

  root 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/links', to: 'static_pages#links', via: 'get'
  match '/signup', to: 'static_pages#signup', via: 'get'
  match '/signin', to: 'students#signin', via: 'post'
  match '/signout', to: 'students#signout',  via: 'post'

end

app/models/video.rb
class Video < ActiveRecord::Base
	require 'fileutils'
	has_many :viewings, dependent: :destroy
	belongs_to :topic

	def imageFile=(inputData)
		self.filename = inputData.original_filename
		if self.topic.nil?
			if Topic.last.blank?
				id = 1
			else
				id = Topic.last.id + 1
			end
		else
			id = self.topic.id
		end
		directory = "public/topics/#{id}/videos"
		FileUtils.mkdir_p(directory)
		File.open(File.join(directory, self.filename), "wb"){|f| f.write(inputData.read)}
	end
	
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	include StudentsHelper
	def show
		@video = Video.find(params[:id])
		@topic = @video.topic
		if !currentStudent.nil? && !currentStudent.viewed?(@video)
			currentStudent.viewed!(@video)
			@viewed = false
		else
			@viewed = true
		end
	end
end

app/views/videos/show.html.erb
<% provide(:title, @video.name) %>
<% content_for :pageBar do %>
	<%= link_to "Topics", topics_path %> > <%= link_to @topic.name, topic_path(@topic) %> > <%= link_to @video.name, video_path(@video) %>
<% end %>
<p><%= @video.name %></p>
<p><%= @video.filename %></p>

   	<% if studentSignedIn? && @viewed%>
		<p>You have already viewed this video</p>
   	<% end %>


<%= video_tag "/topics/#{@video.topic.id}/videos/" + @video.filename, :controls => true %>

<p><%= link_to "Return to Topic", @topic %></p>