config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :tutors do
    get :resume, on: :member
  end
  resources :admins
  resources :departments
  resources :subjects

  resources :topics
  resources :sessions
  resources :hirings, only: [:create, :destroy]

  resources :videos, only: :show
  resources :worksheets, only: :show
  resources :quizzes, only: [:show, :edit, :update] do
    post :grade, on: :member
  end
  resources :certifications, only: :certify do
    get :certify, on: :member
  end

  root 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/links', to: 'static_pages#links', via: 'get'
  match '/signup', to: 'static_pages#signup', via: 'get'
  match '/signin', to: 'students#signin', via: 'post'
  match '/signout', to: 'students#signout',  via: 'post'

end

app/views/layouts/_departments.html.erb
Departments
<ul>
	<% Department.all.each do |department| %>
		<li>
			<%= link_to department.name, department %>
			<ul>
				<% department.subjects.all.each do |subject| %>
					<li>
						<%= link_to subject.name, subject %>
					</li>
				<% end %>
			</ul>
		</li>
	<% end %>
</ul>

app/views/layouts/_header.html.erb
<b><%= link_to "Alpha Omega Tutoring", root_path%></b>
<ul>
	<li><%= link_to "Students", students_path%></li>
	<li><%= link_to "Tutors", tutors_path%></li>
	<li>
		<%= render 'layouts/departments' %>
	</li>
	<li id="signin">
		<% if studentSignedIn? %>
			<%= link_to currentStudent.displayName, currentStudent%>
			<ul>
				<li><%= link_to "Account", student_path(currentStudent)%></li>
				<li><%= link_to "Settings", edit_student_path(currentStudent)%></li>
				<br/>
				<li><%= link_to "Sign Out", signout_path, method: :post%></li>
			</ul>
		<% else %>
			<% if tutorSignedIn? %>
				<%= link_to currentTutor.displayName, currentTutor%>
				<ul>
					<li><%= link_to "Account", tutor_path(currentTutor)%></li>
					<li><%= link_to "Settings", edit_tutor_path(currentTutor)%></li>
					<br/>
					<li><%= link_to "Sign Out", signout_path, method: :post%></li>
				</ul>
			<% else %>
				<% if adminSignedIn? %>
					<%= link_to currentAdmin.displayName, currentAdmin%>
					<ul>
						<li><%= link_to "Account", admin_path(currentAdmin)%></li>
						<li><%= link_to "Settings", edit_admin_path(currentAdmin)%></li>

						<li><%= link_to "Sign Out", signout_path, method: :post %></li>
					</ul>
				<% else %>
					Sign In | <%= link_to "Register", signup_path %>
					<ul>
						<%= form_for(:student, url: signin_path) do |f| %>
						<li>
							<%= f.text_field :email, size: 10, value: "Email", onfocus: "this.value=''", autocomplete: :off%>
						</li>
						<li>
							<%= f.text_field :password, size: 10, value: "Password", onfocus: "this.value=''; this.type='password'"%>
						</li>
						<li>
							<%= f.submit "Sign In" %>
						</li>
						<% end %>
					</ul>
				<% end %>
			<% end %>
		<% end %>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= fullTitle(yield(:title))%></title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div id="navigation">
			<%= render 'layouts/header' %>
		</div>

        <div id="pageBox">
			<% unless current_page?(controller: 'static_pages', action: "home") %>
				<div class="pagebar">
					<%= fullPageBar(yield(:pageBar)) %>
				</div>
			<% end %>
			<div class="row content">
                <% flash.each do |key, value|%>
					<p><%= value%></p>
				<% end%>
                <%= yield %>

            </div>
			<p class="footer">
				<%= link_to "About", about_path%> | <%= link_to "Links", links_path%>
			</p>
		</div>
	</body>
</html>